name: tinyml-research
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - librosa
  - soundfile
  - scikit-learn
  - matplotlib

  - pip:
      - tensorflow==2.15.0
      - tensorflow-model-optimization==0.8.0
